baseURL: "/"
languageCode: "en-us"
theme: "io.alexheld.site-theme"
title: "Alexander Held"

defaultContentLanguage: "en"
paginate: 3

params:
  description: "alex website"

  cta:
    show: true
    cta: "Contact"
    link: "contact"

  copy:
    message: "© 2020 - Alexander Held"

  author: "Alexander Held"

  hero:
    textColor: ""
    imageFile: "developer.svg"

  separator:
    show: false

  contact:
    email: "contact@alexheld.io"
    phone: "+49 157771924534"
    address: "Cologne, Germany"

  social:
    twitter: "https://twitter.com/0_alexheld"
    github: "https://github.com/alex-held"
    xing: "https://www.xing.com/profile/Alexander_Held57"
    stack-overflow: "https://stackoverflow.com/users/10756426/alexander-held"

  languageSwitcher:
    show: true

  fa:
    version: "5.7.2"
    integrity: "sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP"

languages:
  en:
    languageName: "en"
    weight: 1
    contentDir: "content/en"

  de:
    languageName: "de"
    weight: 2
    contentDir: "content/de"
    title: "Das ist der deutsche Titel"
    description: "Das ist die deutsche Beschreibung"
    params:
      form:
        inputNameLabel: "Name"
        inputNamePlaceholder: "Dein Name"
        inputEmailLabel: "E-mail"
        inputEmailPlaceholder: "Deine E-Mail-Adresse"
        inputMsgLabel: "Schreib etwas"
        inputSubmitValue: "Abschicken"
      cta:
        show: true
        cta: "Kontakt"
        link: "de/kontakt/"
