baseURL: "/"
languageCode: "en-us"
theme: "io.alexheld.site-theme"
title: "Alexander Held"

defaultContentLanguage: "en"
paginate: 3

params:
  description: "alex website"

  cta:
    show: true
    cta: "Contact"
    link: "contact"

  copy:
    message: "© 2020 - Alexander Held"

  author: "Alexander Held"

  hero:
    textColor: ""
    imageFile: "developer.svg"

  separator:
    show: false

  contact:
    email: "contact@alexheld.io"
    phone: "+49 157771924534"
    address: "Cologne, Germany"

  posts:
    showAuthor: true
    showDate: true
    showTags: true
    dateFormat: "Monday, Jan, 2006"

  social:
    twitter: "https://twitter.com/0_alexheld"
    github: "https://github.com/alex-held"
    xing: "https://www.xing.com/profile/Alexander_Held57"
    stack-overflow: "https://stackoverflow.com/users/10756426/alexander-held"

  documents:
    resumeUrl: "https://docs.google.com/document/d/e/2PACX-1vQ1LqGPhWyIArZ33aZIdKKDCUM_PBdtrJwxQfQacNpR9ZAdkk-0m067EsfueHShZBeoJ72MUvChEjuo/pub?embedded=true"

  languageSwitcher:
    show: true

  fa:
    version: "5.7.2"
    integrity: "sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP"

  form:
    netlify: true
    action: "https://formspree.io/f/xrgoobja"
    method: "POST"
    inputNameName: "name"
    inputNameLabel: "Name"
    inputNamePlaceholder: "Your name"
    inputEmailName: "email"
    inputEmailLabel: "Email"
    inputEmailPlaceholder: "Your email"
    inputMsgName: "message"
    inputMsgLabel: "Write something"
    inputMsgLength: 750
    inputSubmitValue: "Send"

languages:
  en:
    languageName: "en"
    weight: 1
    contentDir: "content/en"

  de:
    languageName: "de"
    weight: 2
    contentDir: "content/de"
    title: "Alexander Held"
    description: "Das ist die deutsche Beschreibung"
    params:
      form:
        inputNameLabel: "Name"
        inputNamePlaceholder: "Dein Name"
        inputEmailLabel: "E-mail"
        inputEmailPlaceholder: "Deine E-Mail-Adresse"
        inputMsgLabel: "Schreib etwas"
        inputSubmitValue: "Abschicken"
      cta:
        show: true
        cta: "Kontakt"
        link: "de/kontakt/"

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: false
    noClasses: true
    style: monokailight
    tabWidth: 4
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
