version: "3.7"

services:
  site:
    env_file: .env
    image: ${DOCKER_IMAGE}
    build:
      context: .
      dockerfile: site.Dockerfile
      labels: 
      - traefik.http.routers.my-container.rule=Host(`alexheld.io`)
      - traefik.http.services.siteHTTP.loadbalancer.server.port=80
      - traefik.http.services.site.loadbalancer.server.port=80
      - traefik.http.services.siteHTTPS.loadbalancer.server.port=443
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    restart: always
