version: "3.7"

services:
  site:
    # env_file: .prod.env
    image: alexheld/io.alexheld.site:v1.2.4
    restart: always
    networks: 
      - proxy
    build:
      context: .
      dockerfile: site.Dockerfile
      labels: 
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.website-router.rule=Host(`alexheld.io`)"
        - "traefik.http.routers.website-router.tls=true"
        - "traefik.http.routers.website-router.entrypoints=websecure"
        - "traefik.http.routers.website-router.tls.certresolver=le-dns"
        - "traefik.http.routers.website-router.service=website-router"
        - "traefik.http.services.website-router.loadbalancer.server.port=443"

        #traefik.http.routers.site.middlewares: "deny-robots@file, clean-headers@file"
    volumes:
      - /opt/data:/configurations


networks: 
  proxy:
    external: true
