version: "3.7"

services:
  site:
    env_file: .env
    image: ${DOCKER_IMAGE}
    build:
      context: .
      dockerfile: site.Dockerfile
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    restart: always
