version: '3.7'


services:
  website:
      container_name: "io.alexheld.site"
      image: klakegg/hugo:latest
      environment:
        HUGO_ENV: production
        HUGO_BASEURL: https://alexheld.io
      command: server --baseURL https://alexheld.io --appendPort=false
      ports:
        - 1313:1313
      volumes:
        - /root/source/repos/sites/io.alexheld.site/src/:/src
      networks:
        - proxy
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"

        - "traefik.http.routers.website.rule=Host(`alexheld.io`) || Host(`www.alexheld.io`)"
        - "traefik.http.routers.website.tls=true"
        - "traefik.http.routers.website.tls.certresolver=le-dns"
        - "traefik.http.routers.website.entrypoints=websecure"
        - "traefik.http.routers.website.service=website"

        - "traefik.http.services.website.loadbalancer.passhostheader=true"
        - "traefik.http.services.website.loadbalancer.server.port=1313"

networks:
  proxy:
    external: true