version: "3.9"

services:
  frontend:
    env_file: .env
    image: alexheld/io.alexheld.site
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${IO_ALEXHELD_SITE_PORT}:80"
