version: "3.7"

services:
  frontend:
    env_file: .env
    image: alexheld/io.alexheld.site
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    restart: always
